[package]
name = "omni_client"
version = "0.1.0"
edition = "2021"

[dependencies]
omnibox = {git = "https://github.com/hasselalcala/omnibox.git", rev = "fdb8f39cfed9d45941b26abd069d61697a28bb83"}


anyhow = "1.0.90"
near-sdk = "5.5.0"
tokio = { version = "1.40.0", features = ["full"] }